///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace feelingTrackerRanorexTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The closebrowser recording.
    /// </summary>
    [TestModule("8bb613bf-c5ef-44f5-97b8-dc95a4508597", ModuleType.Recording, 1)]
    public partial class closebrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the feelingTrackerRanorexTestRepository repository.
        /// </summary>
        public static feelingTrackerRanorexTestRepository repo = feelingTrackerRanorexTestRepository.Instance;

        static closebrowser instance = new closebrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public closebrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static closebrowser Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable testUrl.
        /// </summary>
        [TestVariable("084f8e2f-9a4b-45dc-a6b4-838265e66b97")]
        public string testUrl
        {
            get { return repo.testUrl; }
            set { repo.testUrl = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'FeelingsTrackerVersion12'.", repo.FeelingsTrackerVersion12.SelfInfo, new RecordItemIndex(0));
            Host.Current.CloseApplication(repo.FeelingsTrackerVersion12.Self, new Duration(0));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
