///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace feelingTrackerRanorexTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the feelingTrackerRanorexTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("e8846197-c75c-4087-b572-9608fef3bcf7")]
    public partial class feelingTrackerRanorexTestRepository : RepoGenBaseFolder
    {
        static feelingTrackerRanorexTestRepository instance = new feelingTrackerRanorexTestRepository();
        feelingTrackerRanorexTestRepositoryFolders.FeelingsTrackerVersion12AppFolder _feelingstrackerversion12;

        /// <summary>
        /// Gets the singleton class instance representing the feelingTrackerRanorexTestRepository element repository.
        /// </summary>
        [RepositoryFolder("e8846197-c75c-4087-b572-9608fef3bcf7")]
        public static feelingTrackerRanorexTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public feelingTrackerRanorexTestRepository() 
            : base("feelingTrackerRanorexTestRepository", "/", null, 0, false, "e8846197-c75c-4087-b572-9608fef3bcf7", ".\\RepositoryImages\\feelingTrackerRanorexTestRepositorye8846197.rximgres")
        {
            _feelingstrackerversion12 = new feelingTrackerRanorexTestRepositoryFolders.FeelingsTrackerVersion12AppFolder(this);
        }

#region Variables

        string _testUrl = "http://localhost:3000";

        /// <summary>
        /// Gets or sets the value of variable testUrl.
        /// </summary>
        [TestVariable("084f8e2f-9a4b-45dc-a6b4-838265e66b97")]
        public string testUrl
        {
            get { return _testUrl; }
            set { _testUrl = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e8846197-c75c-4087-b572-9608fef3bcf7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FeelingsTrackerVersion12 folder.
        /// </summary>
        [RepositoryFolder("8873d1a9-a9bc-4256-a175-64db6a019291")]
        public virtual feelingTrackerRanorexTestRepositoryFolders.FeelingsTrackerVersion12AppFolder FeelingsTrackerVersion12
        {
            get { return _feelingstrackerversion12; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class feelingTrackerRanorexTestRepositoryFolders
    {
        /// <summary>
        /// The FeelingsTrackerVersion12AppFolder folder.
        /// </summary>
        [RepositoryFolder("8873d1a9-a9bc-4256-a175-64db6a019291")]
        public partial class FeelingsTrackerVersion12AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _divwelcomeInfo;

            /// <summary>
            /// Creates a new FeelingsTrackerVersion12  folder.
            /// </summary>
            public FeelingsTrackerVersion12AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FeelingsTrackerVersion12", "/dom[@domain=$testUrl]", parentFolder, 30000, null, false, "8873d1a9-a9bc-4256-a175-64db6a019291", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", ".//input[#'txtUserName'][@visible='true']", 30000, null, "93a3e91f-8c4f-406f-8d43-1a45254581be");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//input[#'txtPassword'][@visible='true']", 30000, null, "745df3dc-5e5d-4935-ab70-3d85af2d73f3");
                _btnloginInfo = new RepoItemInfo(this, "Btnlogin", ".//button[#'btnlogin'][@visible='true']", 30000, null, "6f28fdc5-620a-4ba8-bb49-cfba0a323f4e");
                _divwelcomeInfo = new RepoItemInfo(this, "DivWelcome", ".//div[#'divWelcome'][@visible='true']", 30000, null, "70d5b204-8290-4149-9e1c-b3f879ad7063");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8873d1a9-a9bc-4256-a175-64db6a019291")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8873d1a9-a9bc-4256-a175-64db6a019291")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("93a3e91f-8c4f-406f-8d43-1a45254581be")]
            public virtual Ranorex.InputTag TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("93a3e91f-8c4f-406f-8d43-1a45254581be")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("745df3dc-5e5d-4935-ab70-3d85af2d73f3")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("745df3dc-5e5d-4935-ab70-3d85af2d73f3")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The Btnlogin item.
            /// </summary>
            [RepositoryItem("6f28fdc5-620a-4ba8-bb49-cfba0a323f4e")]
            public virtual Ranorex.ButtonTag Btnlogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Btnlogin item info.
            /// </summary>
            [RepositoryItemInfo("6f28fdc5-620a-4ba8-bb49-cfba0a323f4e")]
            public virtual RepoItemInfo BtnloginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The DivWelcome item.
            /// </summary>
            [RepositoryItem("70d5b204-8290-4149-9e1c-b3f879ad7063")]
            public virtual Ranorex.DivTag DivWelcome
            {
                get
                {
                    return _divwelcomeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivWelcome item info.
            /// </summary>
            [RepositoryItemInfo("70d5b204-8290-4149-9e1c-b3f879ad7063")]
            public virtual RepoItemInfo DivWelcomeInfo
            {
                get
                {
                    return _divwelcomeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
