///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace feelingTrackerRanorexTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubmitFeeling recording.
    /// </summary>
    [TestModule("38b5cd2b-943a-424c-a014-07c24ac5d899", ModuleType.Recording, 1)]
    public partial class SubmitFeeling : ITestModule
    {
        /// <summary>
        /// Holds an instance of the feelingTrackerRanorexTestRepository repository.
        /// </summary>
        public static feelingTrackerRanorexTestRepository repo = feelingTrackerRanorexTestRepository.Instance;

        static SubmitFeeling instance = new SubmitFeeling();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubmitFeeling()
        {
            testUrl = "http://localhost:3000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubmitFeeling Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable testUrl.
        /// </summary>
        [TestVariable("0059b765-ce92-4957-a79b-e80f40882230")]
        public string testUrl
        {
            get { return repo.testUrl; }
            set { repo.testUrl = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeelingsTrackerVersion12.TxtUserName' at 116;14.", repo.FeelingsTrackerVersion12.TxtUserNameInfo, new RecordItemIndex(0));
            repo.FeelingsTrackerVersion12.TxtUserName.Click("116;14", 200);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'reselbob{Escape}' with focus on 'FeelingsTrackerVersion12.TxtUserName'.", repo.FeelingsTrackerVersion12.TxtUserNameInfo, new RecordItemIndex(1));
            repo.FeelingsTrackerVersion12.TxtUserName.PressKeys("reselbob{Escape}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeelingsTrackerVersion12.TxtPassword' at 148;12.", repo.FeelingsTrackerVersion12.TxtPasswordInfo, new RecordItemIndex(2));
            repo.FeelingsTrackerVersion12.TxtPassword.Click("148;12", 200);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'cheese' with focus on 'FeelingsTrackerVersion12.TxtPassword'.", repo.FeelingsTrackerVersion12.TxtPasswordInfo, new RecordItemIndex(3));
            repo.FeelingsTrackerVersion12.TxtPassword.PressKeys("cheese");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeelingsTrackerVersion12.Btnlogin' at 32;16.", repo.FeelingsTrackerVersion12.BtnloginInfo, new RecordItemIndex(4));
            repo.FeelingsTrackerVersion12.Btnlogin.Click("32;16", 200);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Welcome reselbob') on item 'FeelingsTrackerVersion12.DivWelcome'.", repo.FeelingsTrackerVersion12.DivWelcomeInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.FeelingsTrackerVersion12.DivWelcomeInfo, "InnerText", "Welcome reselbob");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
